package com.le.entity;
// Generated 2016-12-15 20:02:46 by Hibernate Tools 3.5.0.Final

/**
 * LeType generated by hbm2java
 */
public class LeType implements java.io.Serializable {

	private Integer letypeId;
	private String type;
	private int startScope;
	private int endScope;

	public LeType() {
	}

	public LeType(String type, int startScope, int endScope) {
		this.type = type;
		this.startScope = startScope;
		this.endScope = endScope;
	}

	public Integer getLetypeId() {
		return this.letypeId;
	}

	public void setLetypeId(Integer letypeId) {
		this.letypeId = letypeId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public int getStartScope() {
		return this.startScope;
	}

	public void setStartScope(int startScope) {
		this.startScope = startScope;
	}

	public int getEndScope() {
		return this.endScope;
	}

	public void setEndScope(int endScope) {
		this.endScope = endScope;
	}

}
