package com.le.entity;
// Generated 2016-12-15 20:02:46 by Hibernate Tools 3.5.0.Final

/**
 * WxParticular generated by hbm2java
 */
public class WxParticular implements java.io.Serializable {

	@Override
	public String toString() {
		return "WxParticular [id=" + id + ", name=" + name + ", eventKey=" + eventKey + ", oldEventKey=" + oldEventKey
				+ ", imageUrl=" + imageUrl + ", leTypeId=" + leTypeId + ", state=" + state + ", contacts=" + contacts
				+ ", mobile=" + mobile + ", leType=" + leType + "]";
	}

	private Integer id;
	private String name;
	private int eventKey;
	private Integer oldEventKey;
	private String imageUrl;
	private int leTypeId;
	private int state;
	private String contacts;
	private String mobile;
    private LeType leType;
	

	public LeType getLeType() {
		return leType;
	}

	public void setLeType(LeType leType) {
		this.leType = leType;
	}

	public WxParticular() {
	}

	public WxParticular(String name, int eventKey, int leTypeId, int state) {
		this.name = name;
		this.eventKey = eventKey;
		this.leTypeId = leTypeId;
		this.state = state;
	}

	public WxParticular(String name, int eventKey, Integer oldEventKey, String imageUrl, int leTypeId, int state,
			String contacts, String mobile) {
		this.name = name;
		this.eventKey = eventKey;
		this.oldEventKey = oldEventKey;
		this.imageUrl = imageUrl;
		this.leTypeId = leTypeId;
		this.state = state;
		this.contacts = contacts;
		this.mobile = mobile;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getEventKey() {
		return this.eventKey;
	}

	public void setEventKey(int eventKey) {
		this.eventKey = eventKey;
	}

	public Integer getOldEventKey() {
		return this.oldEventKey;
	}

	public void setOldEventKey(Integer oldEventKey) {
		this.oldEventKey = oldEventKey;
	}

	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public int getLeTypeId() {
		return this.leTypeId;
	}

	public void setLeTypeId(int leTypeId) {
		this.leTypeId = leTypeId;
	}

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public String getContacts() {
		return this.contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
